version: '3'

services:
  app:
    build: .
    container_name: django-blog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: django-blog-db
    tty: true
    environment:
      - POSTGRES_DB=django_blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - django-blog-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: django-blog-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"

volumes:
  django-blog-pgdata:
    external: true